[package]

name = "ftb"
version = "0.0.1"
authors = ["Peter Atashian <retep998@gmail.com>"]

[dependencies]
regex = "*"
regex_macros = "*"
rustc-serialize = "*"
image = { version = "*", features = ["png"] }
