[package]

name = "ftb"
version = "0.0.1"
authors = ["Peter Atashian <retep998@gmail.com>"]

[dependencies]
regex = "*"
rustc-serialize = "*"

[dependencies.image]
git = "https://github.com/PistonDevelopers/image"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
