[package]
authors = ["Peter Atashian <retep998@gmail.com>"]
name = "ftb"
version = "0.0.1"

[profile.release]
debug = true

[dependencies]
regex = "*"
rustc-serialize = "*"
walkdir = "0.1.5"
image = { default-features = false, features = ["png_codec"], version = "*" }
