[package]

name = "ftb"
version = "0.0.1"
authors = ["Peter Atashian <retep998@gmail.com>"]

[dependencies.image]
git = "https://github.com/PistonDevelopers/rust-image"

[dependencies.colors]
git = "https://github.com/retep998/colors-rs"

[dependencies.lodepng]
git = "https://github.com/retep998/lodepng-rs"
